repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.14
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/python-poetry/poetry
  rev: '1.8.3'
  hooks:
  - id: poetry-export
    args: [
      "-f",
      "requirements.txt",
      "-o",
      "requirements.txt",
      "--without-hashes",
      "--only",
      "main"
    ]
