[tool.poetry]
name = "dogspa-long-reads"
version = "0.1.0"
description = "Depmap Omics Gumbo Syncing, Pre-processing, and Attestation (Long Reads)"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tqdm = "^4.66.1"
oauth2client = "^4.1.3"
google-cloud-storage = "^2.14.0"
functions-framework = "^3.5.0"
pydantic = "^2.5.3"
numpy = "^1.26.3"
pandas = "^2.2.2"
pandera = {extras = ["strategies"], version = "^0.20.3"}
pysam = "^0.22.0"
python-baseconv = "^1.2.2"
google-cloud-logging = "^3.9.0"
python-dotenv = "^1.0.1"
psutil = "^5.9.8"
google-auth = "2.29.0"
ariadne-codegen = "^0.13.0"
nebelung = "^1.0.1"

[tool.poetry.group.dev.dependencies]
ruff = "0.1.14"
ipython = "^8.12"
pyright = "^1.1.378"


[[tool.poetry.source]]
name = "public-python"
url = "https://us-central1-python.pkg.dev/cds-artifacts/public-python/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = [
    "I",  # isort formatting
]
exclude = ["gumbo_gql_client"]

[tool.pyright]
venvPath = "."
venv = ".venv"
include  = ["main.py", "dogspa_long_reads"]
reportInvalidTypeVarUse = "none"
