query GetModelsAndChildren {
  records: model {
    model_id
    cell_line_name
    stripped_cell_line_name
    model_conditions {
      model_condition_id
      omics_profiles {
        profile_id
        datatype
        blacklist_omics
        omics_order_date
        smid_ordered
        smid_returned
        omics_sequencings {
          blacklist
          expected_type
          sequencing_id
          source
          version
          sequencing_alignments {
            id
            url
            index_url
            size
            reference_genome
            sequencing_alignment_source
          }
        }
      }
    }
  }
}
