query LongReadSequencingAlignments {
  records: omics_sequencing(where: { expected_type: { _eq: "long_read_rna" } }) {
    omics_sequencing_id: sequencing_id

    sequencing_alignments {
      sequencing_alignment_source
      size
    }
  }
}
