mutation SetStatus(
  $_username: String!
  $profile_ids: [String!]!
  $status: String!
) {
  set_username(args: { _username: $_username }) {
    username
  }
  update_omics_profile_many(
    updates: {
      where: { profile_id: { _in: $profile_ids } }
      _set: { status: $status }
    }
  ) {
    affected_rows
  }
}
